data/rss.json

add Podcast feed hbSAKABA
https://heartbeats.jp/hbsakaba/

add hbSAKABA

---

data/rss.json

Changed to use feedburner recently 🙏

Fix feed url

---

data/rss.json

タイトルをどうやって入れているのかぱっと見ではわかりませんでしたが、とりあえず JSON 更新しました。
公式ページなどはコミットメッセージを参照ください。

 Add アノニマスですけど何か && だから、海外フリーランス！

---

data/rss.json

最近更新されていないようなので #65 と分けました。
official blog's release entry
http://design-zero.tv/esm/?page_id=20

Add Weekly eBook Strategy (currently not updated)

---

data/rss.json

Anchor.fm URL
https://anchor.fm/crescentradio

Add 三日月ラジオ

---

data/rss.json

Cast for Funのハッシュタグを追加させていただきました。

Update Cast for Fun hashtag

---

data/rss.json

Added 2 feeds
ひよこなもふもふちゃんと技術同人誌.fm
https://mofumofu2.github.io/hiyokoMofu-fm/
pilot boat cast
https://soundcloud.com/pilotboat_cast
\#radiotarosite - モバイルテック時代のライフスタイル
https://anchor.fm/taromatsumura

 Add ひよこなもふもふちゃんと技術同人誌.fm & pilot boat cast & #radiotarosite

---

data/rss.json

- お風呂で情シスhttps://podcasts.apple.com/jp/podcast/%E9%A2%A8%E5%91%82%E5%A0%B4%E3%81%A7%E8%81%9E%E3%81%8D%E3%81%9F%E3%81%84%E6%83%85%E3%82%B7%E3%82%B9%E8%AB%87%E7%BE%A9/id1456006494
- キンスキ ラジオ https://podcasts.apple.com/jp/podcast/%E3%82%AD%E3%83%B3%E3%82%B9%E3%82%AD-%E3%83%A9%E3%82%B8%E3%82%AA/id1441920262

 Add お風呂で情シス && キンスキ ラジオ

---

data/rss.json

Anchor.fm
https://anchor.fm/bitcoiners
YouTube channel
https://www.youtube.com/channel/UCRP9Ij6gL9IViB7MS3Ez9aw

Add ビットコイナー反省会

---

data/rss.json

- FAcast https://facast.net/
- The Potluck Cast https://anchor.fm/the-potluck-cast

Add FACast & The Potluck Cast

---

data/rss.json

先日から新たにPodcastを始めました。
よかったらリストに追加お願いします！🙇 
URL: https://anchor.fm/dosync-radio

Add (dosync radio)

---

data/rss.json

「旅するエンジニア」のPodcastです。
国内・海外を旅しながら働くエンジニアが働き方や国、技術情報などについて雑多に喋ります。

Add Nomadineers Podcast

---

data/rss.json

Add castforfun twitter account

---

data/rss.json

from https://anchor.fm/dokanai

Add Tsundokanai Radio

---

data/rss.json

Add Podcast feed `IJ Cast`
https://cast.innovator.jp.net/
問題なければ追加よろしくお願いします 😃

Add IJ Cast

---

data/rss.json

- Add ashikagacast
- Delete community-drive ( There was 2 same entry. I deleted 1 entry. )
This is my first PR in my life :)

Add ashikagacast and Delete community-drive ( that entry was duplicated )

---

data/rss.json

Add おやかた.am

---

data/rss.json

以下のポッドキャストを追加しました
- Meets.fm
- Off Topic
- PyData JP Podcast
- SiliconValleyWorkers
- 白金鉱業.FM
- ばりへぼデザイン倶楽部
- ミライテック参道DX

Add podcasts

---

data/rss.json

ポッドキャストを追加しました
- AKI空きラジオ
- X-HACK Tokyo Tech Lab
- xR.fm
- Monologura
- Your CIO
- jamming.fm
- アジャイル組織開発サービスreborn

Add more podcasts

---

data/rss.json

HerokuによるポッドキャストCode[ish] JPを追加しました

Add Code[ish] JP

---

data/rss.json

テックやガジェット、Webサービスについて語るPodcastです 😃 
https://remark.life
よろしくおねがいします

Add Remark Life.

---

data/rss.json

- ポッドキャストの追加
- 一部のURLをhttpsに
- 消滅したURLを置き換え

Add podcast

---

data/rss.json

Podcast掲載ありがとうございます！どうぞ、よろしくお願いします。

Add kinokoru's twitter account

---

data/rss.json

Add Yarukinai.fm

---

data/rss.json

Twitterアカウントを追加しました。  
お手すきでマージをよろしくお願いします 🙏

Add ij-cast twitter account

---

data/rss-inactive.json
data/rss.json

https://twitter.com/anitechfm/status/1200401217354006528
公開停止だそうです。ドメインも消えてます。

move anitech inactive

---

data/rss-inactive.json
data/rss.json

アカウントもなくなってます
https://soundcloud.com/railsdm/

move raildm inactive

---

data/rss.json

「クリエイティブが輝ける組織をエンジニアリングする」をテーマに配信中です。
CEOはｼｬｯﾁｮｻﾝのことじゃなくて以下の頭文字です。
- Creative
- Engineering
- Organization
https://anchor.fm/ceofm

add CEO.FM

---

data/rss.json

白金鉱業.FMのtwitterアカウントを追加致しました。宜しくお願いいたします。

add shirokanefm twitter account

---

data/rss.json

フロントエンド系のPodcastを始めましたので、是非掲載お願い致します:bow:
https://anchor.fm/tue-ofuro

add tue_ofuro to rss.json

---

data/rss.json

It’s been a while.
added 23 feeds.
- Autify Podcast https://blog.autify.com/ja/tags/Podcast/1
- CEO.FM https://tchikuba.github.io/blog/2020/02/09/start-ceofm/
- DESIGN FM https://anchor.fm/designfm
- Designput Podcast https://anchor.fm/designput
- DroidKaigi.fm https://droidkaigi.jp/fm/
- ふりかえりam https://anchor.fm/furikaerisuruo/
- ギークなエンジニアを目指す.fm https://shyaginuma.github.io/geek-engineer-future/
- GULab https://1t1d.gu.net/
- Happy Tech Talkers' Podcast https://note.com/httpradio
- Koiki.fm https://anchor.fm/koiki.fm
- meands.fm https://meands.fm/
- 名無しさんのポッドキャスト https://toris.io/podcast/
- PROPOTYPE - プロポタイプ https://propo.fm/propotype
- エンジニアのキャリアストーリー「ROLE MODEL」 https://pitpa.jp/playlist/JxtCyoZTDZ
- ScanNetSecurity 最新セキュリティ情報 Podcast https://scan.netsecurity.ne.jp/
- Serverless NOW …

Add 23 feeds

---

data/rss.json

- dotlike_podcast https://dotlike.ch/ep/2
- ie69 https://anchor.fm/ie69

Add feeds dotlike_podcast and ie69

---

data/rss.json

* Yokohama North AM https://anchor.fm/yokohama-north-am

Add feeds Yokohama North AM

---

data/rss.json

こんにちは、[Interaxion](https://interaxion-podcast.github.io/)という podcast をやっている者です。登録していただけるとうれしいです。

Add feed: interaxion

---

data/rss-inactive.json
data/rss.json

https://omsubi.work は https://reborn.inc に移転しています
同時にPodcastも公開終了したようです

move omsubi a.k.a. テスト inactive

---

data/rss.json

EM.FM の Twitter アカウント (https://twitter.com/devemfm) を追加し、Researchat の Twitter アカウント (https://twitter.com/researchat_fm) を修正しました。

add EM.FM twitter account

---

data/rss.json

ref. https://twitter.com/t_wada/status/1300285944424062976

Add texta.fm

---

data/rss.json

- AI酒場
- DojoCast
- IBM Developer Podcast Japanese Edition
- AIスタートアップ井戸端会議
- マチマチFM
- マスクドアナライズのIT業界チャラリブレ
- outer-heaven.fm
- ラジテクFM
- 検索.fm
- さばラジ！
- yota.fm
- ゆるふわてとらん！

add a dozen podcasts

---

data/rss.json

- ブロックチェーンジャム
- みりらじお
- Secure Liaison

add three podcasts and fix some data

---

data/rss.json

https://twitter.com/tomoaki_imai/status/1301777954909765633

Add Today I Learned

---

data/rss.json

- 46fm
- Forkwell Tech Cast
- hikifune.fm
- just4fun.fm
- Tensor FM

add 5 podcasts

---

data/rss-inactive.json
data/rss.json

配信を終了しましたので、inactiveへ移動させました。  
マージよろしくお願いします :pray:

Move ij-cast inactive

---

data/rss.json

初めまして [あらB.fm](https://anchor.fm/arkbfm) という podcast を配信しているものです。ぜひ Podcast Freaks へご登録いただければ幸いです。

Add arkbfm

---

data/rss.json

koiki.fmのツイッターアカウントとハッシュタグの情報を更新しました。

---

data/rss.json

@naokazuterada こんにちは！追加していただきありがとうございます！情報を追加したのでマージお願いします:bow:

Add twitter and hastag in van-engineers

---

data/rss.json

ToraLab.fm は、虎の穴ラボのエンジニアが業務や技術・働き方についてざっくばらんにお届けする番組として、配信中です。
直近では、以下をテーマに配信しています。
- UI
- データベース
- kotlin
https://anchor.fm/toranoanalab

add ToraLab.fm

---

data/rss.json

Add devchat.fm
https://anchor.fm/devchat-fm/episodes/12--KyashUbie--1-with-konifarsys1yagi-en546g

Add devchat.fm

---

data/rss.json

dely堀江さんのpodcast
https://anchor.fm/good-to-great

Add good to great

---

data/rss.json

Add e34.fm

---

data/rss.json

Add resize.fm

---

data/rss.json

ref: https://anchor.fm/basuke-suzuki

Add Basuke's Tech Talk

---

data/rss.json

Add keepalive.fm

---

data/rss.json

https://anchor.fm/agiletechexpo

Add あじゃてくちゃんねる

---

data/rss.json

今年に入ってから始めたテック系のポッドキャストです。
HPなどはまだないですが、Anchorで配信しています。
https://podcastfreaks.com/request/
上記URLからはリクエストを送っていませんが、送ったほうが良いでしょうか？
また、data.jsonがパット見 abc 順でしたので、間にいれましたが、末尾に追加のほうが良いでしょうか？
そのあたりご確認いただければと思います。
よろしくお願い致します。

ココナッツテックをdata.jsonへ追加しました。

---

data/rss.json

> cookpad Design Radio By クックパッド株式会社
> クックパッドのデザイナーが「いいプロダクトをつくる」ためにやっていること・考えていることなどを話す、実験的な番組です。
> 平日毎日Twitterスペースで公開収録をする予定です。
https://anchor.fm/cookpad-design-radio

Add cookpad Design Radio

---

data/rss.json

@takaishi と @june29 で運営している https://anchor.fm/kimagurefm を追加したいです。よろしくお願いします :pray:

キマグレエフエムを追加する

---

data/rss.json

ref: https://twitter.com/h_doxas/status/1436162302844157970

Add normalizefm
